### ISSUE TITLE
我下载的懒人包,我想使用chatglm-6b-int8的模型,strategy应该选哪个?

### ISSUE THREAD

**Issue by starsliao** [l15y/wenda#279]
我看配置文件里面默认是这样的
```
  glm6b: 
     path: "model/chatglm-6b-int4"
     #glm模型位置"
     strategy: "cuda fp16"
     #cuda fp16	 所有glm模型 要直接跑在gpu上都可以使用这个参数
     #cuda fp16i8	 fp16原生模型 要自行量化为int8跑在gpu上可以使用这个参数
     #cuda fp16i4	 fp16原生模型 要自行量化为int4跑在gpu上可以使用这个参数
```
我想使用chatglm-6b-int8的模型,strategy是用`cuda fp16`吗?还是改成`cuda fp16i8`

另外注释里面写的:
`fp16原生模型 要自行量化为int8`,是什么意思?下载了chatglm-6b-int8的模型 还需要进行其它操作吗?
